ui:
  color: yes
import:
  move: yes
  resume: yes
  incremental: yes
  detail: yes
  group_albums: yes
  bell: yes
musicbrainz:
  genres: yes
paths:
  default: $albumartist/[$year]$atypes $album/$track $title
plugins:
  - chroma
  - autobpm
  - fetchart
  - embedart
  - lyrics
  - mbsync
  - replaygain
  - parentwork
  - scrub
  - albumtypes
  - thumbnails
  - lastgenre
  - bandcamp
  - xtractor
fetchart:
  quality: 75
  enforce_ratio: yes
embedart:
  quality: 75
lyrics:
  sources: [lrclib, genius, tekstowo]
  synced: yes
  force: yes
replaygain:
  backend: ffmpeg
parentwork:
  auto: yes
thumbnails:
  dolphin: yes
xtractor:
  essentia_extractor: /home/jaugusto/Programs/essentia-extractors/streaming_extractor_music
  extractor_profile:
    highlevel:
      svm_models:
        - /home/jaugusto/Programs/essentia-extractors/danceability.history
        - /home/jaugusto/Programs/essentia-extractors/gender.history
        - /home/jaugusto/Programs/essentia-extractors/genre_rosamerica.history
        - /home/jaugusto/Programs/essentia-extractors/mood_acoustic.history
        - /home/jaugusto/Programs/essentia-extractors/mood_aggresive.history
        - /home/jaugusto/Programs/essentia-extractors/mood_electronic.history
        - /home/jaugusto/Programs/essentia-extractors/mood_happy.history
        - /home/jaugusto/Programs/essentia-extractors/mood_sad.history
        - /home/jaugusto/Programs/essentia-extractors/mood_party.history
        - /home/jaugusto/Programs/essentia-extractors/mood_relaxed.history
        - /home/jaugusto/Programs/essentia-extractors/voice_instrumental.history
        - /home/jaugusto/Programs/essentia-extractors/moods_mirex.history
