ui:
  color: yes
import:
  move: yes
  resume: yes
  incremental: yes
  detail: yes
  group_albums: yes
  bell: yes
musicbrainz:
  genres: yes
paths:
  default: $albumartist/[$year]$atypes $album/$track $title
plugins:
  - chroma
  - fetchart
  - embedart
  - lyrics
  - mbsync
  - replaygain
  - parentwork
  - scrub
  - albumtypes
  - thumbnails
  - lastgenre
  - bandcamp
fetchart:
  quality: 75
  enforce_ratio: yes
embedart:
  quality: 75
lyrics:
  sources: [lrclib, genius, tekstowo]
  synced: yes
  force: yes
replaygain:
  backend: ffmpeg
parentwork:
  auto: yes
thumbnails:
  dolphin: yes
