[git]
autoCommit = true
autoPush = true

[edit]
command = "nvim"
apply = true

[data.packages]
brew = [
  "eza",
  "fastfetch",
  "fd",
  "ffmpeg",
  "fzf",
  "gh",
  "imagemagick",
  "jq",
  "lazygit",
  "neovim",
  "poppler",
  "resvg",
  "ripgrep",
  "yazi",
  "zoxide",
  "kew",
  "mise",
  "picotool",
  "yt-dlp",
  "aria2",
  "zellij",
  "tldr",
  "meson",
  "oh-my-posh",
]
dnf.packages = [
  "kitty",
  "arm-none-eabi-gcc-cs-c++",
  "arm-none-eabi-newlib",
  "libusb1-devel",
  "hidapi-devel",
  "fish",
]
dnf.groups = ["c-development", "development-tools"]
