
brew = [
  "antidote",
  "eza",
  "fastfetch",
  "fd",
  "ffmpeg",
  "fzf",
  "gh",
  "imagemagick",
  "jq",
  "lazygit",
  "neovim",
  "poppler",
  "resvg",
  "ripgrep",
  "yazi",
  "zoxide",
  "starship",
  "kew",
  "mise",
  "rustup",
  "picotool",
  "yt-dlp",
  "aria2",
]
