version = 3
final_space = true
shell_integration = true

[upgrade]
source = 'cdn'
interval = '168h'
auto = false
notice = false

[transient_prompt]
foreground = '#FFBD00'
template = '⮞ '

[[blocks]]
type = 'prompt'
alignment = 'left'

[[blocks.segments]]
template = "{{ .UserName }}'s "
foreground = '#FFBD00'
type = 'session'
style = 'plain'

[[blocks.segments]]
template = '{{ .Path }}/ '
foreground = '#00C6F7'
type = 'path'
style = 'plain'

[blocks.segments.properties]
style = 'folder'

[[blocks.segments]]
template = '<#ffffff>on</> {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '
foreground = '#F62F2E'
type = 'git'
style = 'plain'

[blocks.segments.properties]
fetch_status = true

[[blocks.segments]]
template = '<#ffffff>via</>  {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }} '
foreground = '#98C379'
type = 'node'
style = 'plain'

[blocks.segments.properties]
fetch_version = true

[[blocks]]
type = 'prompt'
alignment = 'right'

[[blocks.segments]]
type = 'status'
template = "{{ if eq .Code 0 }}\uf00c{{ else }}\uf071 {{ reason .Code }} {{ end }}"
foreground = "#F62F2E"

[[blocks.segments]]
trailing_diamond = ' '
template = 'RAM:{{ (div ((sub .PhysicalTotalMemory .PhysicalAvailableMemory)|float64) 1073741824.0) }}/{{ (div .PhysicalTotalMemory 1073741824.0) }}GB '
foreground = '#85C980'
type = 'sysinfo'
style = 'diamond'

[[blocks.segments]]
leading_diamond = '┋'
template = ' {{ .FormattedMs }} '
foreground = '#ffffff'
type = 'executiontime'
style = 'diamond'

[blocks.segments.properties]
style = 'roundrock'
threshold = 0.0

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
template = '⮞ '
foreground = '#FFBD00'
type = 'text'
style = 'plain'
